@extends('layouts.app')
@section('title', '在线地图')
@section('content')
<div class="mx-auto max-w-7xl space-y-5 sm:space-y-6">
 <section class="relative overflow-hidden rounded-2xl border border-emerald-400/20 bg-gradient-to-br from-emerald-600 via-teal-600 to-cyan-700 px-5 py-6 text-white shadow-lg sm:px-7 sm:py-8"><div class="pointer-events-none absolute -right-16 -top-20 h-64 w-64 rounded-full bg-white/10 blur-2xl"></div><div class="relative flex flex-col gap-5 md:flex-row md:items-center md:justify-between"><div><div class="mb-2 inline-flex items-center gap-2 rounded-full border border-white/20 bg-white/10 px-3 py-1 text-xs font-semibold tracking-wider text-emerald-50"><span class="h-2 w-2 animate-pulse rounded-full bg-emerald-200"></span>实时地图</div><h1 class="text-2xl font-bold tracking-tight sm:text-3xl">服务器在线地图</h1><p class="mt-2 max-w-xl text-sm leading-6 text-emerald-50 sm:text-base">实时探索服务器世界、查看地标和在线玩家动态。</p></div><button id="mapFullscreen" type="button" class="inline-flex items-center justify-center self-start rounded-xl border border-white/30 bg-white/10 px-4 py-2.5 text-sm font-semibold text-white transition hover:bg-white/20">全屏地图</button></div></section>
 <section id="mapPanel" class="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div id="mapToolbar" class="flex items-center justify-between gap-3 border-b border-slate-100 bg-slate-50/70 px-4 py-3 sm:px-5"><div class="flex items-center gap-3"><div class="flex h-10 w-10 items-center justify-center rounded-xl bg-emerald-100 text-lg">🗺️</div><div><h2 class="font-bold text-slate-800">实时地图</h2><p class="text-xs text-slate-500">地图会缓存在当前浏览器中，加快再次访问速度</p></div></div><div class="flex items-center gap-2 text-xs text-slate-500"><span class="h-2 w-2 rounded-full bg-emerald-500"></span><span>实时服务</span></div></div><div id="mapFrameWrap" class="relative min-h-0 bg-slate-100"><iframe id="dynmapFrame" src="{{ $dynmapUrl }}" title="Minecraft 在线地图" class="block h-[72vh] min-h-[560px] w-full border-0 bg-slate-100" loading="eager" referrerpolicy="strict-origin-when-cross-origin">你的浏览器不支持内嵌地图。</iframe><div id="mapFallback" class="pointer-events-none absolute inset-0 hidden items-center justify-center bg-slate-900/80 p-6 text-center text-white"><div><p class="text-lg font-bold">地图加载失败</p><p class="mt-2 text-sm text-slate-300">请刷新页面后重试。</p></div></div></div></section>
 <p class="text-center text-xs text-slate-400">地图数据由服务器 Dynmap 实时提供</p>
</div>
<style>
html:has(#mapPanel:fullscreen),body:has(#mapPanel:fullscreen){margin:0!important;padding:0!important;overflow:hidden!important;background:#0f172a!important}
#mapPanel:fullscreen{box-sizing:border-box;width:100vw;height:100dvh;margin:0!important;padding:0!important;border:0!important;border-radius:0!important;background:#0f172a!important;overflow:hidden!important}
#mapPanel:fullscreen #mapToolbar{display:none!important}
#mapPanel:fullscreen #mapFrameWrap{position:absolute!important;inset:0!important;width:100%!important;height:100%!important;margin:0!important;padding:0!important;background:#0f172a!important;overflow:hidden!important}
#mapPanel:fullscreen #dynmapFrame{display:block!important;width:100%!important;height:100%!important;min-height:0!important;margin:0!important;padding:0!important;border:0!important;background:#0f172a!important}
@media(max-width:640px){#dynmapFrame{height:72vh;min-height:480px}}
</style>
<script>(()=>{const panel=document.getElementById('mapPanel'),frame=document.getElementById('dynmapFrame'),button=document.getElementById('mapFullscreen'),fallback=document.getElementById('mapFallback');const sync=()=>button.textContent=document.fullscreenElement?'退出全屏':'全屏地图';button.addEventListener('click',async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await panel.requestFullscreen()}catch(e){fallback.classList.remove('hidden')}});document.addEventListener('fullscreenchange',sync);frame.addEventListener('error',()=>fallback.classList.remove('hidden'));sync()})();</script>
@endsection