@extends('layouts.app')
@section('title', '在线地图')
@section('content')
<div class="mx-auto max-w-7xl space-y-5 sm:space-y-6">
 <section class="relative overflow-hidden rounded-2xl border border-emerald-400/20 bg-gradient-to-br from-emerald-600 via-teal-600 to-cyan-700 px-5 py-6 text-white shadow-lg sm:px-7 sm:py-8"><div class="pointer-events-none absolute -right-16 -top-20 h-64 w-64 rounded-full bg-white/10 blur-2xl"></div><div class="relative flex flex-col gap-5 md:flex-row md:items-center md:justify-between"><div><div class="mb-2 inline-flex items-center gap-2 rounded-full border border-white/20 bg-white/10 px-3 py-1 text-xs font-semibold tracking-wider text-emerald-50"><span class="h-2 w-2 animate-pulse rounded-full bg-emerald-200"></span>DYNMAP · LIVE</div><h1 class="text-2xl font-bold tracking-tight sm:text-3xl">服务器在线地图</h1><p class="mt-2 max-w-xl text-sm leading-6 text-emerald-50 sm:text-base">实时探索服务器世界、查看地标和在线玩家动态。</p></div><div class="flex flex-wrap gap-2"><a href="{{ $dynmapUrl }}" target="_blank" rel="noopener noreferrer" class="inline-flex items-center justify-center rounded-xl bg-white px-4 py-2.5 text-sm font-semibold text-emerald-700 shadow-sm transition hover:bg-emerald-50">在新窗口打开 <span class="ml-1">↗</span></a><button id="mapFullscreen" type="button" class="inline-flex items-center justify-center rounded-xl border border-white/30 bg-white/10 px-4 py-2.5 text-sm font-semibold text-white transition hover:bg-white/20">全屏地图</button></div></div></section>
 <section class="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div class="flex flex-col gap-3 border-b border-slate-100 bg-slate-50/70 px-4 py-3 sm:flex-row sm:items-center sm:justify-between sm:px-5"><div class="flex items-center gap-3"><div class="flex h-10 w-10 items-center justify-center rounded-xl bg-emerald-100 text-lg">🗺️</div><div><h2 class="font-bold text-slate-800">Dynmap 实时地图</h2><p class="text-xs text-slate-500">使用官方原版地图界面</p></div></div><div class="flex items-center gap-2 text-xs text-slate-500"><span class="h-2 w-2 rounded-full bg-emerald-500"></span><span>实时服务</span></div></div><div id="mapFrameWrap" class="relative bg-slate-100"><iframe id="dynmapFrame" src="{{ $dynmapUrl }}" title="Minecraft Dynmap 在线地图" class="block h-[72vh] min-h-[560px] w-full border-0 bg-slate-100" loading="eager" referrerpolicy="strict-origin-when-cross-origin">你的浏览器不支持内嵌地图，请使用上方“在新窗口打开”。</iframe><div id="mapFallback" class="pointer-events-none absolute inset-0 hidden items-center justify-center bg-slate-900/80 p-6 text-center text-white"><div><p class="text-lg font-bold">地图无法内嵌显示</p><p class="mt-2 text-sm text-slate-300">请在新窗口中打开完整 Dynmap。</p><a href="{{ $dynmapUrl }}" target="_blank" rel="noopener noreferrer" class="pointer-events-auto mt-4 inline-flex rounded-xl bg-emerald-500 px-4 py-2.5 font-semibold text-white">打开地图 ↗</a></div></div></div></section>
 <p class="text-center text-xs text-slate-400">地图数据由服务器 Dynmap 实时提供</p>
</div>
<script>(()=>{const wrap=document.getElementById('mapFrameWrap'),frame=document.getElementById('dynmapFrame');document.getElementById('mapFullscreen').onclick=()=>{if(wrap.requestFullscreen)wrap.requestFullscreen()};frame.addEventListener('error',()=>document.getElementById('mapFallback').classList.remove('hidden'))})();</script>
@endsection